substitutions:
  pwm_freq: 500 Hz
  
esphomeyaml:
  name: h801_skylight
  platform: ESP8266
  board: esp8285
  build_path: build

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.2.0.67
    gateway: 10.2.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '10.2.0.1'
  port: 1883

logger:
  baud_rate: 115200

ota:

output:
  - id: pwm_b
    platform: esp8266_pwm
    pin: 12
    frequency: ${pwm_freq}
  - id: pwm_r
    platform: esp8266_pwm
    pin: 13
    frequency: ${pwm_freq}
  - id: pwm_g
    platform: esp8266_pwm
    pin: 15
    frequency: ${pwm_freq}
  - id: pwm_w1
    platform: esp8266_pwm
    pin: 14
    frequency: ${pwm_freq}
  - id: pwm_w2
    platform: esp8266_pwm
    pin: 4
    frequency: ${pwm_freq}
    
light:
  - platform: monochromatic
    name: "Kit_r"
    output: pwm_r
  - platform: monochromatic
    name: "Kit_g"
    output: pwm_g
  - platform: monochromatic
    name: "Kit_b"
    output: pwm_b
  - platform: monochromatic
    name: "Kit_w1"
    output: pwm_w1
  - platform: monochromatic
    name: "Kit_w2"
    output: pwm_w2
