esphome:
  name: bed_bar_asher
  platform: esp8266
  board: esp12e
  build_path: build

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ''
  use_address: 10.2.0.36
  
logger:
  baud_rate: 115200
  level: DEBUG
  
ota:

mqtt:
  broker: '10.2.0.1'
  port: 1883
  username: ''
  password: ''

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO14
    num_leds: 38
    rgb_order: GRB
    name: "strip"
    
binary_sensor:
  - platform: gpio
    name: "button 1"
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 10ms
  - platform: gpio
    name: "button 2"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 10ms
  - platform: gpio
    name: "button 3"
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 10ms
  - platform: gpio
    name: "button 4"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 10ms
 
