esphome:
  name: nightlight_${location}
  platform: esp8266
  board: ${board}
  # or esp12e
  build_path: build

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${wifi_addr}
  domain: '.bigasterisk.com'

mqtt:
  broker: '10.2.0.1'
  port: 1883
  username: ''
  password: ''
  
logger:
  baud_rate: 115200
  level: INFO
  
ota:
