# jump IO0 to GND on the board for programming


esphome:
  name: garage_hall_cam
  platform: ESP32
  board: nodemcu-32s
  build_path: garage_hall_cam

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ''
  use_address: 10.2.0.74
     
mqtt:
 broker: '10.2.0.1'
 port: 1883
 username: ''
 password: ''
  
logger:
  baud_rate: 115200
  level: DEBUG
  
ota:

# Serves multipart mime stream of jpegs at GET /

# gst-launch-1.0  souphttpsrc location=http://10.2.0.74/ do-timestamp=true ! multipartdemux ! jpegdec ! autovideosink