esphome:
  name: nightlight_ari
  platform: esp8266
  board: esp12e
  build_path: build

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.2.0.96
#  domain: '.bigasterisk.com'

mqtt:
  broker: '10.2.0.1'
  port: 1883
  username: ''
  password: ''
  
logger:
  baud_rate: 115200
  level: INFO
  
ota:


dallas:
  - pin: GPIO5
    update_interval: 10s

sensor:
  - platform: dallas
    index: 0
    name: temperature

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO4
    num_leds: 16
    rgb_order: GRB
    name: "rgb16"
