esphome:
  name: sonoff_4
  platform: esp8266
  board: esp01_1m
  build_path: build

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: 10.2.0.96
#  domain: '.bigasterisk.com'

mqtt:
  broker: '10.2.0.1'
  port: 1883
  username: ''
  password: ''
  
logger:
  baud_rate: 115200
  level: INFO
  
ota:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
