esphome:
  name: frontdoorlock
  platform: ESP32
  board: lolin32
  build_path: .
  arduino_version: espressif32@>=1.4.0

switch:
  - platform: gpio
    pin: 2
    name: "strike"

wifi:
  ssid: ''
  password: ''

mqtt:
  broker: '10.2.0.1'
  port: 10210
  keepalive: 5s
  
logger:
  baud_rate: 115200
  level: DEBUG
  
