# Stubs for greplin.scales.aggregation_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class AggregationTest(unittest.TestCase):
    def testNoData(self) -> None: ...
    def testRegex(self) -> None: ...
