# Stubs for greplin.scales.bottlehandler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def bottlestats(server_name: Any, path: str = ...): ...
def register_stats_handler(app: Any, server_name: Any, prefix: str = ...) -> None: ...
