# Stubs for greplin.scales.cyclonehandler (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import cyclone.web
from greplin.scales import tornadolike

class StatsHandler(tornadolike.Handler, cyclone.web.RequestHandler): ...
