# Stubs for greplin.scales.loop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def installStatsLoop(statsFile: Any, statsDelay: Any) -> None: ...
