# Stubs for greplin.scales.samplestats_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class UniformSampleTest(unittest.TestCase):
    def testGaussian(self) -> None: ...

class ExponentiallyDecayingReservoirTest(unittest.TestCase):
    def testGaussian(self) -> None: ...
    def testWithRescale(self) -> None: ...
