# Stubs for greplin.scales.timer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def RepeatTimer(interval: Any, function: Any, iterations: int = ..., *args: Any, **kwargs: Any): ...
