# Stubs for greplin.scales.tornadolike (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Handler:
    serverName: Any = ...
    def initialize(self, serverName: Any) -> None: ...
    def get(self, path: Any) -> None: ...
