# Stubs for greplin.scales.util_test (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class AtomicValueTest(unittest.TestCase):
    def testUpdate(self) -> None: ...
    def testGetAndSet(self) -> None: ...
    def testAddAndGet(self) -> None: ...
