from typing import Any, Optional

class IDelayedCall:
    def getTime(self) -> Any: ...
    def cancel(self) -> None: ...
    def delay(self, secondsLater: Any) -> None: ...
    def reset(self, secondsFromNow: Any) -> None: ...
    def active(self) -> None: ...
    

class ReactorType: # abridged
    def listenTCP(self, port: Any, factory: Any, backlog: int = ..., interface: str = ...) -> None: ...
    def seconds(self) -> None: ...
    def callLater(self, delay: Any, callable: Any, *args: Any, **kw: Any) -> IDelayedCall: ...
    def getDelayedCalls(self) -> None: ...
    def callFromThread(self, callable: Any, *args: Any, **kw: Any) -> None: ...
    def callInThread(self, callable: Any, *args: Any, **kwargs: Any) -> None: ...
    running: Any = ...
    def resolve(self, name: Any, timeout: int = ...) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def crash(self) -> None: ...
    def iterate(self, delay: int = ...) -> None: ...
    def fireSystemEvent(self, eventType: Any) -> None: ...
    def addSystemEventTrigger(self, phase: Any, eventType: Any, callable: Any, *args: Any, **kw: Any) -> None: ...
    def removeSystemEventTrigger(self, triggerID: Any) -> None: ...
    def callWhenRunning(self, callable: Any, *args: Any, **kw: Any) -> None: ...
    

reactor = ReactorType()
