apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: mqtt-to-rdf
build:
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05"
      timezone: "Local"
  artifacts:
  - image: bang5:5000/mqtt_to_rdf_image
deploy:
  kubectl:
    manifests:
    - deploy.yaml
