FROM bang6:5000/base_pi

WORKDIR /opt

RUN apt-get install -y python-clang-5.0 libclang-5.0-dev libnfc5 libfreefare0 libnfc-dev libfreefare-dev 
RUN pip install git+https://github.com/drewp/ctypeslib.git@enable-modules-flag

COPY build_ctypes_modules.sh ./

CMD ["/bin/sh", "/opt/build_ctypes_modules.sh"]