# Stubs for rdflib (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from rdflib.term import URIRef, BNode, Literal, Variable
from rdflib.namespace import Namespace
from rdflib.graph import  Dataset, Graph, ConjunctiveGraph
from rdflib.namespace import RDF, RDFS, OWL, XSD

