# Stubs for rdflib.parser (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from io import StringIO as BytesIO

class Parser:
    def __init__(self): ...
    def parse(self, source, sink): ...

class InputSource: # subclass of xmlreader
  ...


class StringInputSource(InputSource):
    def __init__(self, value, system_id=None): ...

class URLInputSource(InputSource):
    url = ...  # type: Any
    content_type = ...  # type: Any
    def __init__(self, system_id=None, format=None): ...

class FileInputSource(InputSource):
    file = ...  # type: Any
    def __init__(self, file): ...
